# Python stubs generated by omniidl from idl/Writer.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "Writer"
#
__name__ = "Writer"
_0_Writer = omniORB.openModule("Writer", r"idl/Writer.idl")
_0_Writer__POA = omniORB.openModule("Writer__POA", r"idl/Writer.idl")


# interface mWriter
_0_Writer._d_mWriter = (omniORB.tcInternal.tv_objref, "IDL:Writer/mWriter:1.0", "mWriter")
omniORB.typeMapping["IDL:Writer/mWriter:1.0"] = _0_Writer._d_mWriter
_0_Writer.mWriter = omniORB.newEmptyClass()
class mWriter :
    _NP_RepositoryId = _0_Writer._d_mWriter[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Writer.mWriter = mWriter
_0_Writer._tc_mWriter = omniORB.tcInternal.createTypeCode(_0_Writer._d_mWriter)
omniORB.registerType(mWriter._NP_RepositoryId, _0_Writer._d_mWriter, _0_Writer._tc_mWriter)

# mWriter operations and attributes
mWriter._d_oCurrentCursorPositionX = ((), (omniORB.tcInternal.tv_float, ), None)
mWriter._d_oCurrentCursorPositionY = ((), (omniORB.tcInternal.tv_float, ), None)
mWriter._d_gotoStart = ((omniORB.tcInternal.tv_boolean, ), (), None)
mWriter._d_gotoEnd = ((omniORB.tcInternal.tv_boolean, ), (), None)
mWriter._d_gotoStartOfLine = ((omniORB.tcInternal.tv_boolean, ), (), None)
mWriter._d_gotoEndOfLine = ((omniORB.tcInternal.tv_boolean, ), (), None)

# mWriter object reference
class _objref_mWriter (CORBA.Object):
    _NP_RepositoryId = mWriter._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def oCurrentCursorPositionX(self, *args):
        return _omnipy.invoke(self, "oCurrentCursorPositionX", _0_Writer.mWriter._d_oCurrentCursorPositionX, args)

    def oCurrentCursorPositionY(self, *args):
        return _omnipy.invoke(self, "oCurrentCursorPositionY", _0_Writer.mWriter._d_oCurrentCursorPositionY, args)

    def gotoStart(self, *args):
        return _omnipy.invoke(self, "gotoStart", _0_Writer.mWriter._d_gotoStart, args)

    def gotoEnd(self, *args):
        return _omnipy.invoke(self, "gotoEnd", _0_Writer.mWriter._d_gotoEnd, args)

    def gotoStartOfLine(self, *args):
        return _omnipy.invoke(self, "gotoStartOfLine", _0_Writer.mWriter._d_gotoStartOfLine, args)

    def gotoEndOfLine(self, *args):
        return _omnipy.invoke(self, "gotoEndOfLine", _0_Writer.mWriter._d_gotoEndOfLine, args)

    __methods__ = ["oCurrentCursorPositionX", "oCurrentCursorPositionY", "gotoStart", "gotoEnd", "gotoStartOfLine", "gotoEndOfLine"] + CORBA.Object.__methods__

omniORB.registerObjref(mWriter._NP_RepositoryId, _objref_mWriter)
_0_Writer._objref_mWriter = _objref_mWriter
del mWriter, _objref_mWriter

# mWriter skeleton
__name__ = "Writer__POA"
class mWriter (PortableServer.Servant):
    _NP_RepositoryId = _0_Writer.mWriter._NP_RepositoryId


    _omni_op_d = {"oCurrentCursorPositionX": _0_Writer.mWriter._d_oCurrentCursorPositionX, "oCurrentCursorPositionY": _0_Writer.mWriter._d_oCurrentCursorPositionY, "gotoStart": _0_Writer.mWriter._d_gotoStart, "gotoEnd": _0_Writer.mWriter._d_gotoEnd, "gotoStartOfLine": _0_Writer.mWriter._d_gotoStartOfLine, "gotoEndOfLine": _0_Writer.mWriter._d_gotoEndOfLine}

mWriter._omni_skeleton = mWriter
_0_Writer__POA.mWriter = mWriter
omniORB.registerSkeleton(mWriter._NP_RepositoryId, mWriter)
del mWriter
__name__ = "Writer"

#
# End of module "Writer"
#
__name__ = "Writer_idl"

_exported_modules = ( "Writer", )

# The end.
